package com.aionn.identity.application.service;

import com.aionn.identity.application.dto.user.command.CancelAccountDeletionCommand;
import com.aionn.identity.application.dto.user.command.ChangeEmailCommand;
import com.aionn.identity.application.dto.user.command.ChangePhoneCommand;
import com.aionn.identity.application.dto.user.command.RequestAccountDeletionCommand;
import com.aionn.identity.application.dto.user.command.RequestDataExportCommand;
import com.aionn.identity.application.dto.user.command.VerifyEmailCommand;
import com.aionn.identity.application.dto.user.view.DataExportRequestView;
import com.aionn.identity.application.dto.user.view.DeletionRequestView;
import com.aionn.identity.application.dto.user.view.UserActionOutcomeView;
import com.aionn.identity.application.dto.user.view.UserProfileView;
import com.aionn.identity.application.port.out.auth.AuthSessionPersistencePort;
import com.aionn.identity.application.port.out.auth.RefreshTokenStore;
import com.aionn.identity.application.port.out.user.AccountChangeNotifier;
import com.aionn.identity.application.port.out.user.AccountDeletionPort;
import com.aionn.identity.application.port.out.user.DataExportPort;
import com.aionn.identity.application.port.out.user.EmailOtpSender;
import com.aionn.identity.application.port.out.user.OtpChannel;
import com.aionn.identity.application.port.out.user.PhoneOtpSender;
import com.aionn.identity.application.port.out.user.UserOtpChallengeStore;
import com.aionn.identity.application.port.out.user.UserOtpPurpose;
import com.aionn.identity.application.port.out.user.UserPersistencePort;
import com.aionn.identity.application.port.out.user.model.UserOtpChallenge;
import com.aionn.identity.domain.exception.IdentityErrorCode;
import com.aionn.identity.domain.exception.IdentityException;
import com.aionn.identity.domain.model.AuthSession;
import com.aionn.identity.domain.model.IdentityUser;
import com.aionn.identity.domain.valueobject.AuthSessionStatus;
import com.aionn.sharedkernel.util.OtpGenerator;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.stream.Collectors;

/**
 * Account self-service operations: email/phone change with OTP, account
 * deletion request and data export request.
 *
 * <p>
 * Notable correctness/security improvements over the original
 * implementation:
 * <ul>
 * <li>OTPs are generated by {@link OtpGenerator}, which is backed by
 * {@link java.security.SecureRandom}.</li>
 * <li>{@code confirmEmailChange} / {@code confirmPhoneChange} re-check
 * uniqueness before applying the change to close the TOCTOU window
 * between {@code requestOtp} and {@code confirmOtp}.</li>
 * <li>After a confirmed change all active sessions are revoked so a stolen
 * session cannot ride a hijacked email / phone change.</li>
 * <li>The previous email / phone receives a notification through
 * {@link AccountChangeNotifier} so a legitimate user can detect a
 * takeover attempt.</li>
 * </ul>
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class AccountManagementService {

    public static final String ACTION_SEND_OTP = "SEND_OTP";

    private static final int OTP_EXPIRY_SECONDS = 300;
    private static final int OTP_MAX_ATTEMPTS = 5;
    private static final int ACCOUNT_DELETION_GRACE_DAYS = 30;

    private final UserPersistencePort userPersistencePort;
    private final EmailOtpSender emailOtpSender;
    private final PhoneOtpSender phoneOtpSender;
    private final UserOtpChallengeStore userOtpChallengeStore;
    private final AccountDeletionPort accountDeletionPort;
    private final DataExportPort dataExportPort;
    private final AuthSessionPersistencePort authSessionPersistencePort;
    private final RefreshTokenStore refreshTokenStore;
    private final AccountChangeNotifier accountChangeNotifier;

    public UserActionOutcomeView verifyPrimaryEmail(VerifyEmailCommand command) {
        if (ACTION_SEND_OTP.equalsIgnoreCase(command.action())) {
            sendVerifyPrimaryEmailOtp(command.userId());
            return new UserActionOutcomeView("OTP_SENT", "OTP sent to email", null);
        }
        confirmVerifyPrimaryEmailOtp(command.userId(), command.otpCode());
        return new UserActionOutcomeView("EMAIL_VERIFIED", "Email verified", null);
    }

    public UserActionOutcomeView changeEmail(ChangeEmailCommand command) {
        if (ACTION_SEND_OTP.equalsIgnoreCase(command.action())) {
            requestEmailChangeOtp(command.userId(), command.newEmail());
            return new UserActionOutcomeView("OTP_SENT", "OTP sent to new email", null);
        }
        UserProfileView profile = confirmEmailChange(command.userId(), command.otpCode());
        return new UserActionOutcomeView("EMAIL_UPDATED", "Email updated", profile);
    }

    public UserActionOutcomeView changePhone(ChangePhoneCommand command) {
        if (ACTION_SEND_OTP.equalsIgnoreCase(command.action())) {
            requestPhoneChangeOtp(command.userId(), command.newPhone());
            return new UserActionOutcomeView("OTP_SENT", "OTP sent to new phone", null);
        }
        UserProfileView profile = confirmPhoneChange(command.userId(), command.otpCode());
        return new UserActionOutcomeView("PHONE_UPDATED", "Phone updated", profile);
    }

    public DeletionRequestView requestAccountDeletion(RequestAccountDeletionCommand command) {
        return requestAccountDeletion(command.userId());
    }

    public void cancelAccountDeletion(CancelAccountDeletionCommand command) {
        cancelAccountDeletion(command.userId());
    }

    public DataExportRequestView requestDataExport(RequestDataExportCommand command) {
        return requestDataExport(command.userId());
    }

    private void sendVerifyPrimaryEmailOtp(String userId) {
        IdentityUser user = getActiveUser(userId);
        if (user.getEmail() == null || user.getEmail().isBlank()) {
            throw new IdentityException(IdentityErrorCode.EMAIL_ALREADY_EXISTS, "User has no primary email");
        }
        String otpCode = OtpGenerator.generate6DigitOtp();
        userOtpChallengeStore.save(new UserOtpChallenge(
                userId,
                UserOtpPurpose.VERIFY_PRIMARY_EMAIL,
                OtpChannel.EMAIL,
                user.getEmail(),
                otpCode,
                null,
                LocalDateTime.now().plusSeconds(OTP_EXPIRY_SECONDS),
                0));
        emailOtpSender.sendOtp(user.getEmail(), otpCode);
        log.info("Verification OTP sent to email for user: {}", userId);
    }

    private void confirmVerifyPrimaryEmailOtp(String userId, String otpCode) {
        IdentityUser user = getActiveUser(userId);
        UserOtpChallenge challenge = getChallenge(
                userId,
                UserOtpPurpose.VERIFY_PRIMARY_EMAIL,
                IdentityErrorCode.EMAIL_VERIFICATION_NOT_FOUND);
        validateOtp(challenge, otpCode);
        user.verifyEmail();
        userPersistencePort.save(user);
        userOtpChallengeStore.delete(userId, UserOtpPurpose.VERIFY_PRIMARY_EMAIL);
        log.info("Email verified for user: {}", userId);
    }

    private void requestEmailChangeOtp(String userId, String newEmail) {
        IdentityUser user = getActiveUser(userId);
        if (newEmail == null || newEmail.isBlank()) {
            throw new IdentityException(IdentityErrorCode.EMAIL_ALREADY_EXISTS, "New email must not be blank");
        }
        userPersistencePort.findByIdentity(newEmail)
                .filter(existing -> !existing.getUserId().equals(user.getUserId()))
                .ifPresent(existing -> {
                    throw new IdentityException(IdentityErrorCode.EMAIL_ALREADY_EXISTS);
                });

        String otpCode = OtpGenerator.generate6DigitOtp();
        userOtpChallengeStore.save(new UserOtpChallenge(
                userId,
                UserOtpPurpose.CHANGE_EMAIL,
                OtpChannel.EMAIL,
                newEmail,
                otpCode,
                newEmail,
                LocalDateTime.now().plusSeconds(OTP_EXPIRY_SECONDS),
                0));
        emailOtpSender.sendOtp(newEmail, otpCode);
        log.info("Email change OTP sent to new email for user: {}", userId);
    }

    private UserProfileView confirmEmailChange(String userId, String otpCode) {
        IdentityUser user = getActiveUser(userId);
        UserOtpChallenge challenge = getChallenge(userId, UserOtpPurpose.CHANGE_EMAIL,
                IdentityErrorCode.EMAIL_CHANGE_NOT_FOUND);
        validateOtp(challenge, otpCode);

        // Re-check uniqueness right before applying: a concurrent registration may
        // have grabbed the same email between requestOtp and confirmOtp.
        userPersistencePort.findByIdentity(challenge.pendingValue())
                .filter(existing -> !existing.getUserId().equals(user.getUserId()))
                .ifPresent(existing -> {
                    throw new IdentityException(IdentityErrorCode.EMAIL_ALREADY_EXISTS);
                });

        String oldEmail = user.getEmail();
        user.updateEmail(challenge.pendingValue());
        IdentityUser saved = userPersistencePort.save(user);
        userOtpChallengeStore.delete(userId, UserOtpPurpose.CHANGE_EMAIL);

        revokeAllSessions(userId);
        if (oldEmail != null && !oldEmail.isBlank()) {
            try {
                accountChangeNotifier.notifyEmailChanged(userId, oldEmail, saved.getEmail());
            } catch (RuntimeException ex) {
                log.warn("Failed to notify previous email of change for user {}", userId, ex);
            }
        }
        log.info("Email changed for user: {}", userId);
        return toProfileView(saved);
    }

    private void requestPhoneChangeOtp(String userId, String newPhone) {
        getActiveUser(userId);
        if (newPhone == null || newPhone.isBlank()) {
            throw new IdentityException(IdentityErrorCode.PHONE_ALREADY_EXISTS, "New phone must not be blank");
        }
        if (userPersistencePort.existsByPhone(newPhone)) {
            throw new IdentityException(IdentityErrorCode.PHONE_ALREADY_EXISTS);
        }

        String otpCode = OtpGenerator.generate6DigitOtp();
        userOtpChallengeStore.save(new UserOtpChallenge(
                userId,
                UserOtpPurpose.CHANGE_PHONE,
                OtpChannel.PHONE,
                newPhone,
                otpCode,
                newPhone,
                LocalDateTime.now().plusSeconds(OTP_EXPIRY_SECONDS),
                0));
        phoneOtpSender.sendOtp(newPhone, otpCode);
        log.info("Phone change OTP sent to new phone for user: {}", userId);
    }

    private UserProfileView confirmPhoneChange(String userId, String otpCode) {
        IdentityUser user = getActiveUser(userId);
        UserOtpChallenge challenge = getChallenge(userId, UserOtpPurpose.CHANGE_PHONE,
                IdentityErrorCode.PHONE_CHANGE_NOT_FOUND);
        validateOtp(challenge, otpCode);

        if (userPersistencePort.existsByPhone(challenge.pendingValue())
                && !challenge.pendingValue().equals(user.getPhone())) {
            throw new IdentityException(IdentityErrorCode.PHONE_ALREADY_EXISTS);
        }

        String oldPhone = user.getPhone();
        user.updatePhone(challenge.pendingValue());
        IdentityUser saved = userPersistencePort.save(user);
        userOtpChallengeStore.delete(userId, UserOtpPurpose.CHANGE_PHONE);

        revokeAllSessions(userId);
        if (oldPhone != null && !oldPhone.isBlank()) {
            try {
                accountChangeNotifier.notifyPhoneChanged(userId, oldPhone, saved.getPhone());
            } catch (RuntimeException ex) {
                log.warn("Failed to notify previous phone of change for user {}", userId, ex);
            }
        }
        log.info("Phone changed for user: {}", userId);
        return toProfileView(saved);
    }

    private DeletionRequestView requestAccountDeletion(String userId) {
        getActiveUser(userId);
        if (accountDeletionPort.findPendingByUserId(userId).isPresent()) {
            throw new IdentityException(IdentityErrorCode.ACCOUNT_DELETION_ALREADY_REQUESTED);
        }
        LocalDateTime scheduledDeletionAt = LocalDateTime.now().plusDays(ACCOUNT_DELETION_GRACE_DAYS);
        DeletionRequestView result = accountDeletionPort.save(userId, scheduledDeletionAt);
        log.info("Account deletion requested for user: {}, scheduled at: {}", userId, scheduledDeletionAt);
        return result;
    }

    private void cancelAccountDeletion(String userId) {
        getActiveUser(userId);
        if (accountDeletionPort.findPendingByUserId(userId).isEmpty()) {
            throw new IdentityException(IdentityErrorCode.ACCOUNT_DELETION_NOT_FOUND);
        }
        accountDeletionPort.cancel(userId);
        log.info("Account deletion canceled for user: {}", userId);
    }

    private DataExportRequestView requestDataExport(String userId) {
        getActiveUser(userId);
        if (dataExportPort.hasActiveRequest(userId)) {
            throw new IdentityException(IdentityErrorCode.DATA_EXPORT_ALREADY_IN_PROGRESS);
        }
        DataExportRequestView result = dataExportPort.save(userId);
        log.info("Data export requested for user: {}", userId);
        return result;
    }

    private void revokeAllSessions(String userId) {
        var sessions = authSessionPersistencePort.findByUserId(userId);
        for (AuthSession session : sessions) {
            if (AuthSessionStatus.ACTIVE.equals(session.getStatus())) {
                session.revoke();
                refreshTokenStore.revokeBySessionId(session.getSessionId());
            }
        }
        authSessionPersistencePort.saveAll(sessions);
    }

    private UserOtpChallenge getChallenge(String userId, UserOtpPurpose purpose, IdentityErrorCode notFoundCode) {
        return userOtpChallengeStore.find(userId, purpose)
                .orElseThrow(() -> new IdentityException(notFoundCode));
    }

    private void validateOtp(UserOtpChallenge challenge, String otpCode) {
        if (otpCode == null || otpCode.isBlank()) {
            throw new IdentityException(IdentityErrorCode.OTP_REQUIRED);
        }
        if (challenge.expiresAt().isBefore(LocalDateTime.now())) {
            userOtpChallengeStore.delete(challenge.userId(), challenge.purpose());
            throw new IdentityException(IdentityErrorCode.OTP_EXPIRED);
        }
        if (!challenge.otpCode().equals(otpCode)) {
            int attempts = challenge.attempts() + 1;
            if (attempts >= OTP_MAX_ATTEMPTS) {
                userOtpChallengeStore.delete(challenge.userId(), challenge.purpose());
                throw new IdentityException(IdentityErrorCode.OTP_ATTEMPTS_EXCEEDED);
            }
            userOtpChallengeStore.save(challenge.withAttempts(attempts));
            throw new IdentityException(IdentityErrorCode.OTP_INVALID);
        }
    }

    private IdentityUser getActiveUser(String userId) {
        IdentityUser user = userPersistencePort.findById(userId)
                .orElseThrow(() -> new IdentityException(IdentityErrorCode.USER_NOT_FOUND));
        if (!user.isActive()) {
            throw new IdentityException(IdentityErrorCode.USER_INACTIVE);
        }
        return user;
    }

    private UserProfileView toProfileView(IdentityUser user) {
        return new UserProfileView(
                user.getUserId(),
                user.getEmail(),
                user.getPhone(),
                user.getUsername(),
                user.getDisplayName(),
                user.getAvatarUrl(),
                user.getRoles().stream().map(Enum::name).collect(Collectors.toSet()),
                user.getStatus().name(),
                user.getEmailVerifiedAt(),
                user.getPhoneVerifiedAt(),
                user.getCreatedAt());
    }
}

