package com.aionn.identity.application.service;

import com.aionn.identity.application.port.out.security.MfaPersistencePort;
import com.aionn.identity.application.port.out.security.PasswordHasher;
import com.aionn.identity.application.port.out.security.SecurityAuditPort;
import com.aionn.identity.application.port.out.security.UserSecurityPort;
import com.aionn.identity.domain.exception.IdentityErrorCode;
import com.aionn.identity.domain.exception.IdentityException;
import com.aionn.sharedkernel.util.OtpGenerator;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * MFA management. Enable/disable require password re-authentication; backup
 * codes are 8-digit numerics generated by {@link OtpGenerator} and hashed with
 * the project's {@link PasswordHasher} before storage.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class MfaService {

    private static final int BACKUP_CODE_COUNT = 8;

    private final UserSecurityPort userSecurityPort;
    private final MfaPersistencePort mfaPersistencePort;
    private final SecurityAuditPort securityAuditPort;
    private final PasswordHasher passwordHasher;

    public boolean enableMfa(String userId, String password, String ipAddress) {
        log.info("Enabling MFA for user: {}", userId);
        var user = getUserSecurityData(userId);
        verifyPassword(user, password);
        mfaPersistencePort.updateMfaStatus(userId, true);
        securityAuditPort.saveAuditLog(userId, "MFA_ENABLED", "MFA enabled", ipAddress);
        return true;
    }

    public boolean disableMfa(String userId, String password, String ipAddress) {
        log.info("Disabling MFA for user: {}", userId);
        var user = getUserSecurityData(userId);
        verifyPassword(user, password);
        mfaPersistencePort.updateMfaStatus(userId, false);
        securityAuditPort.saveAuditLog(userId, "MFA_DISABLED", "MFA disabled", ipAddress);
        return false;
    }

    /**
     * Regenerate backup codes. Requires the user's current password to defeat
     * session-hijack attacks: a stolen access token alone cannot mint new
     * codes.
     */
    public List<String> regenerateBackupCodes(String userId, String password, String ipAddress) {
        log.info("Regenerating backup codes for user: {}", userId);
        var user = getUserSecurityData(userId);
        verifyPassword(user, password);

        mfaPersistencePort.deleteBackupCodes(userId);

        List<String> rawCodes = java.util.stream.IntStream.range(0, BACKUP_CODE_COUNT)
                .mapToObj(i -> OtpGenerator.generate8DigitOtp())
                .toList();
        List<String> codeHashes = rawCodes.stream()
                .map(passwordHasher::hash)
                .toList();
        mfaPersistencePort.saveBackupCodes(userId, codeHashes);

        securityAuditPort.saveAuditLog(userId, "MFA_BACKUP_CODES_REGENERATED", "Backup codes regenerated", ipAddress);
        return rawCodes;
    }

    private void verifyPassword(UserSecurityPort.UserSecurityData user, String password) {
        if (password == null || password.isBlank()
                || user.passwordHash() == null
                || !passwordHasher.matches(password, user.passwordHash())) {
            log.warn("MFA operation rejected for user {} due to bad password", user.userId());
            throw new IdentityException(IdentityErrorCode.INVALID_CREDENTIALS);
        }
    }

    private UserSecurityPort.UserSecurityData getUserSecurityData(String userId) {
        return userSecurityPort.findById(userId)
                .orElseThrow(() -> new IdentityException(IdentityErrorCode.USER_NOT_FOUND));
    }
}

