package com.aionn.identity.application.service;

import com.aionn.identity.application.port.out.auth.AuthSessionPersistencePort;
import com.aionn.identity.application.port.out.auth.RefreshTokenStore;
import com.aionn.identity.application.port.out.security.PasswordHasher;
import com.aionn.identity.application.port.out.security.PasswordResetPort;
import com.aionn.identity.application.port.out.security.SecurityAuditPort;
import com.aionn.identity.application.port.out.security.UserSecurityPort;
import com.aionn.identity.application.port.out.user.AccountChangeNotifier;
import com.aionn.identity.domain.exception.IdentityErrorCode;
import com.aionn.identity.domain.exception.IdentityException;
import com.aionn.identity.domain.model.AuthSession;
import com.aionn.identity.domain.valueobject.AuthSessionStatus;
import com.aionn.sharedkernel.util.IdGenerator;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.security.SecureRandom;
import java.time.LocalDateTime;
import java.util.Base64;

/**
 * Password change/reset operations.
 *
 * <p>
 * Reset tokens are random 256-bit values (URL-safe base64) generated by
 * {@link SecureRandom}, valid for 15 minutes, single-use. We do
 * <strong>not</strong>
 * return the token to the API caller; instead we deliver it through the
 * configured notifier so the requesting party must control the email/phone of
 * the account.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class PasswordResetService {

    private static final SecureRandom SECURE_RANDOM = new SecureRandom();
    private static final int RESET_TOKEN_BYTES = 32;
    private static final int RESET_TOKEN_TTL_MINUTES = 15;
    private static final int MIN_PASSWORD_LENGTH = 8;
    private static final int MAX_PASSWORD_LENGTH = 128;

    private final UserSecurityPort userSecurityPort;
    private final PasswordResetPort passwordResetPort;
    private final SecurityAuditPort securityAuditPort;
    private final PasswordHasher passwordHasher;
    private final AuthSessionPersistencePort authSessionPersistencePort;
    private final RefreshTokenStore refreshTokenStore;
    private final AccountChangeNotifier accountChangeNotifier;

    public void changePassword(String userId, String currentPassword, String newPassword, String ipAddress) {
        log.info("Processing password change for user: {}", userId);
        validateNewPassword(newPassword);
        if (currentPassword != null && currentPassword.equals(newPassword)) {
            throw new IdentityException(IdentityErrorCode.OTP_INVALID,
                    "New password must differ from the current password");
        }

        var user = getUserSecurityData(userId);
        if (!passwordHasher.matches(currentPassword, user.passwordHash())) {
            log.warn("Failed password change for user {} - invalid current password", userId);
            throw new IdentityException(IdentityErrorCode.INVALID_CREDENTIALS);
        }

        passwordResetPort.updatePassword(userId, passwordHasher.hash(newPassword));
        revokeOtherSessions(userId);
        securityAuditPort.saveAuditLog(userId, "PASSWORD_CHANGED", "User changed password", ipAddress);
        accountChangeNotifier.notifyPasswordChanged(userId, "self-service");
    }

    /**
     * Initiate a password reset. Always returns silently regardless of whether
     * the identity matches a user, to prevent enumeration. The actual reset
     * token is delivered to the user out of band.
     */
    public void requestPasswordReset(String identity, String ipAddress) {
        log.info("Processing password reset request");
        var user = userSecurityPort.findByIdentity(identity);
        if (user.isEmpty()) {
            log.debug("Password reset requested for unknown identity (silently ignored)");
            return;
        }

        byte[] bytes = new byte[RESET_TOKEN_BYTES];
        SECURE_RANDOM.nextBytes(bytes);
        String token = Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);

        passwordResetPort.savePasswordResetToken(token, user.get().userId(),
                LocalDateTime.now().plusMinutes(RESET_TOKEN_TTL_MINUTES));
        securityAuditPort.saveAuditLog(user.get().userId(), "PASSWORD_RESET_REQUESTED",
                "User requested password reset", ipAddress);
        // Token is delivered via notifier; never log raw token nor return it.
        accountChangeNotifier.notifyPasswordChanged(user.get().userId(), "reset-request:" + token);
    }

    public void completePasswordReset(String token, String newPassword, String ipAddress) {
        log.info("Processing password reset completion");
        validateNewPassword(newPassword);

        var data = passwordResetPort.findPasswordResetToken(token)
                .orElseThrow(() -> {
                    log.warn("Invalid password reset token presented");
                    return new IdentityException(IdentityErrorCode.VERIFICATION_TOKEN_INVALID);
                });
        if (data.expiresAt().isBefore(LocalDateTime.now())) {
            passwordResetPort.deletePasswordResetToken(token);
            throw new IdentityException(IdentityErrorCode.OTP_EXPIRED);
        }

        passwordResetPort.updatePassword(data.userId(), passwordHasher.hash(newPassword));
        passwordResetPort.deletePasswordResetToken(token);
        revokeOtherSessions(data.userId());
        securityAuditPort.saveAuditLog(data.userId(), "PASSWORD_RESET_COMPLETED",
                "Password reset completed with token", ipAddress);
        accountChangeNotifier.notifyPasswordChanged(data.userId(), "reset");
    }

    private void revokeOtherSessions(String userId) {
        var sessions = authSessionPersistencePort.findByUserId(userId);
        for (AuthSession session : sessions) {
            if (AuthSessionStatus.ACTIVE.equals(session.getStatus())) {
                session.revoke();
                refreshTokenStore.revokeBySessionId(session.getSessionId());
            }
        }
        authSessionPersistencePort.saveAll(sessions);
    }

    private void validateNewPassword(String newPassword) {
        if (newPassword == null || newPassword.length() < MIN_PASSWORD_LENGTH
                || newPassword.length() > MAX_PASSWORD_LENGTH) {
            throw new IdentityException(IdentityErrorCode.INVALID_CREDENTIALS,
                    "Password must be between " + MIN_PASSWORD_LENGTH + " and "
                            + MAX_PASSWORD_LENGTH + " characters");
        }
        // Lightweight complexity rule: at least one letter and one digit.
        boolean hasLetter = newPassword.chars().anyMatch(Character::isLetter);
        boolean hasDigit = newPassword.chars().anyMatch(Character::isDigit);
        if (!hasLetter || !hasDigit) {
            throw new IdentityException(IdentityErrorCode.INVALID_CREDENTIALS,
                    "Password must contain at least one letter and one digit");
        }
    }

    private UserSecurityPort.UserSecurityData getUserSecurityData(String userId) {
        return userSecurityPort.findById(userId)
                .orElseThrow(() -> new IdentityException(IdentityErrorCode.USER_NOT_FOUND));
    }

    /**
     * Used for {@link #requestPasswordReset(String, String)} signature
     * compatibility.
     */
    @SuppressWarnings("unused")
    private static String unusedTokenPlaceholder() {
        return IdGenerator.ulid();
    }
}

