INSERT INTO notification_templates (
    template_id, event_type, channel, category, locale, subject, content, placeholders, version, is_active
) VALUES
    (
        'id_pwd_reset_em_vi',
        'IDENTITY_PASSWORD_RESET_REQUESTED',
        'EMAIL',
        'SECURITY',
        'vi-VN',
        'Yeu cau dat lai mat khau',
        'Ban vua yeu cau dat lai mat khau. Ma dat lai cua ban la {{resetToken}}. Neu khong phai ban, hay bo qua email nay va doi mat khau ngay.',
        '["resetToken"]'::jsonb,
        1,
        TRUE
    ),
    (
        'id_pwd_reset_in_vi',
        'IDENTITY_PASSWORD_RESET_REQUESTED',
        'IN_APP',
        'SECURITY',
        'vi-VN',
        'Yeu cau dat lai mat khau',
        'He thong vua ghi nhan mot yeu cau dat lai mat khau cho tai khoan cua ban.',
        '[]'::jsonb,
        1,
        TRUE
    ),
    (
        'id_pwd_reset_push_vi',
        'IDENTITY_PASSWORD_RESET_REQUESTED',
        'PUSH',
        'SECURITY',
        'vi-VN',
        'Yeu cau dat lai mat khau',
        'He thong vua ghi nhan mot yeu cau dat lai mat khau.',
        '[]'::jsonb,
        1,
        TRUE
    ),
    (
        'id_pwd_changed_em_vi',
        'IDENTITY_PASSWORD_CHANGED',
        'EMAIL',
        'SECURITY',
        'vi-VN',
        'Mat khau da duoc thay doi',
        'Mat khau cua ban vua duoc thay doi qua {{channelHint}}. Neu khong phai ban, hay doi mat khau ngay lap tuc.',
        '["channelHint"]'::jsonb,
        1,
        TRUE
    ),
    (
        'id_pwd_changed_in_vi',
        'IDENTITY_PASSWORD_CHANGED',
        'IN_APP',
        'SECURITY',
        'vi-VN',
        'Mat khau da duoc thay doi',
        'Mat khau cua ban vua duoc thay doi qua {{channelHint}}.',
        '["channelHint"]'::jsonb,
        1,
        TRUE
    ),
    (
        'id_pwd_changed_push_vi',
        'IDENTITY_PASSWORD_CHANGED',
        'PUSH',
        'SECURITY',
        'vi-VN',
        'Mat khau da duoc thay doi',
        'Mat khau cua ban vua duoc thay doi.',
        '[]'::jsonb,
        1,
        TRUE
    ),
    (
        'id_email_changed_em_vi',
        'IDENTITY_EMAIL_CHANGED',
        'EMAIL',
        'SECURITY',
        'vi-VN',
        'Email tai khoan da thay doi',
        'Email tai khoan cua ban vua duoc doi tu {{oldEmail}} sang {{newEmail}}. Neu khong phai ban, hay doi mat khau ngay.',
        '["oldEmail","newEmail"]'::jsonb,
        1,
        TRUE
    ),
    (
        'id_email_changed_in_vi',
        'IDENTITY_EMAIL_CHANGED',
        'IN_APP',
        'SECURITY',
        'vi-VN',
        'Email tai khoan da thay doi',
        'Email tai khoan cua ban vua duoc doi sang {{newEmail}}.',
        '["newEmail"]'::jsonb,
        1,
        TRUE
    ),
    (
        'id_email_changed_pushv',
        'IDENTITY_EMAIL_CHANGED',
        'PUSH',
        'SECURITY',
        'vi-VN',
        'Email da thay doi',
        'Email tai khoan cua ban vua duoc cap nhat.',
        '[]'::jsonb,
        1,
        TRUE
    ),
    (
        'id_phone_changed_em_vi',
        'IDENTITY_PHONE_CHANGED',
        'EMAIL',
        'SECURITY',
        'vi-VN',
        'So dien thoai da thay doi',
        'So dien thoai tai khoan cua ban vua duoc doi tu {{oldPhone}} sang {{newPhone}}. Neu khong phai ban, hay doi mat khau ngay.',
        '["oldPhone","newPhone"]'::jsonb,
        1,
        TRUE
    ),
    (
        'id_phone_changed_in_vi',
        'IDENTITY_PHONE_CHANGED',
        'IN_APP',
        'SECURITY',
        'vi-VN',
        'So dien thoai da thay doi',
        'So dien thoai tai khoan cua ban vua duoc doi sang {{newPhone}}.',
        '["newPhone"]'::jsonb,
        1,
        TRUE
    ),
    (
        'id_phone_changed_psh',
        'IDENTITY_PHONE_CHANGED',
        'PUSH',
        'SECURITY',
        'vi-VN',
        'So dien thoai da thay doi',
        'So dien thoai tai khoan cua ban vua duoc cap nhat.',
        '[]'::jsonb,
        1,
        TRUE
    ),
    (
        'id_phone_changed_sms',
        'IDENTITY_PHONE_CHANGED',
        'SMS',
        'SECURITY',
        'vi-VN',
        NULL,
        'So dien thoai tai khoan cua ban vua duoc doi sang {{newPhone}}. Neu khong phai ban, hay doi mat khau ngay.',
        '["newPhone"]'::jsonb,
        1,
        TRUE
    );
